name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{DOCKER_USERNAME}}
        password: ${{DOCKER_TOKEN}}
        
    - name: Build the Docker image
      run: |
        docker build AmCart --file AmCart/ProductService/Dockerfile --tag drexcdp/amcart-product-service:latest
        docker push drexcdp/amcart-product-service:latest
